### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by jamesjimmy88** [hako-mikan/sd-webui-negpip#11]
I get this crazy console spam while generating with this extension; only enabling the extension doesn't cause this, it only happens by actively using it.
Running on version 1.6.0 python: 3.10.6 torch: 2.0.0+cu118 xformers: 0.0.20.dev526 gradio: 3.41.2
Extension version 7d4defb3 2023-09-22
![Untitled-1](https://github.com/hako-mikan/sd-webui-negpip/assets/58559532/4e86fc37-d672-4951-8214-e851cf6cf585)

**Comment by hako-mikan** [comment]
Fixed.
