### ISSUE TITLE
常時オンにできるようにしたい

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-negpip#12]
いつもお世話になっております。

最新バージョンでは、マイナス指定のプロンプトが無ければ生成には影響が無いようになっていると思いますが、それでしたら常時オン（オンにしたままWebUIを終了したあと、次回起動時にオフにならない）にしておきたいと考えています。
（WebUIのプロンプトスタイル機能を多用しているのですが、マイナス指定の入ったプロンプトを呼び出して使う際、NegPiPをオンにし忘れて出力結果が変わって慌てることが多いため）

LoRA BlockWeight拡張は常時オンにできるようになっているようなので、それと同じになるとよいかなと思いました。

**Comment by JunJi-JiaYue** [comment]
横からで申し訳ありませんが、`ui-config.json`の`"customscript/negpip.py/txt2img/active/value"`の値をtrueにするのはどうでしょうか？

**Comment by hako-mikan** [comment]
私も`ui-config.json`の`customscript/negpip.py/txt2img/active/value`をいじるのを推奨したいところでしたが、
慣れていない人も多いと思うので設定できるボタンを作りました。

**Comment by w-e-w** [comment]
Webui -> Settings -> Defaults
WebUI状態保存の機能があります

https://github.com/hako-mikan/sd-webui-negpip/assets/40751091/a0784e63-ee02-4fb4-b8a5-30286839cc48

**Comment by JujoHotaru** [comment]
@hako-mikan 

ご対応ありがとうございました！
更新してみたのですが、WebUI起動時に以下のエラーが出て、拡張機能が使えなくなってしまっているようです。

```
*** Error loading script: negpip.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py", line 14, in <module>
        import scripts.attention
    ModuleNotFoundError: No module named 'scripts.attention'
```

**Comment by JujoHotaru** [comment]
Pythonは3.10を使用しています。

**Comment by hako-mikan** [comment]
凡ミスでした。
今は直ってます。

**Comment by hako-mikan** [comment]
@w-e-w 
そのような方法があるとは気づいていませんでした。
ありがとうございます！

**Comment by JujoHotaru** [comment]
さっそくの修正ご対応ありがとうございました。
WebUI自体の設定保存の情報もいただきましたが、拡張機能部分に設定が設置されているのもわかりやすくて有用と思います。
これにてクローズさせていただきます。
