### ISSUE TITLE
negpipがactiveの際にControlnetのIp-adapterが効かなくなるようです

### ISSUE THREAD

**Issue by nazikero** [hako-mikan/sd-webui-negpip#13]
いつもお世話になっています。negpipのお陰で表現の幅が広がってすごく楽しいです。
最近ControlnetにIp-adapterという、画像をプロンプトにする昨日が追加されたんですが
どちらもプロンプトに大きく影響する拡張ゆえか、Ipadapterが出力したプロンプトがどこかでかき消されてしまっているようです。
エラーなどは出力されていないので不思議なのですが・・・解決する方法は無いでしょうか

**Comment by hako-mikan** [comment]
いろいろ試してみたのですが、デノイズの課程で重要な部分について双方でプロセスを取り合っている状況でして、どちらかしか有効にならないようです。どちらも有効にしようとすると、共同でひとつのコードを作ることになりそうなので難しいです。

**Comment by nazikero** [comment]
そうだったのですね。お忙しい中検証してくださいりありがとうございました！
