### ISSUE TITLE
発動した場合、PNG Infoに情報を埋め込んでほしい

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-negpip#14]
いつもお世話になっております。

プロンプトにマイナス指定が存在してNegPiPが発動した場合、生成画像のPNG InfoにNegPiPが発動したことを示すメタデータを埋め込んでもらえると、将来メタデータで情報整理したり、投稿サイトに登録した際に使用した拡張機能のリストを出す機能などで使えるのではないかと思いました。

余談ですが、現状、マイナス指定のプロンプトを含んだままでCivitAIに画像投稿しているのですが、NegPiPを使用していることを示すことができずにいます。これは現状では仕方ないですね…

**Comment by hako-mikan** [comment]
埋め込むようにしました。ついでにPNG infoから設定を読み出したときに反映されるようにもなりました。

**Comment by JujoHotaru** [comment]
こちらも動作確認いたしました。ご対応ありがとうございました。
