### ISSUE TITLE
Error message between each step (generation still works)

### ISSUE THREAD

**Issue by Priestru** [hako-mikan/sd-webui-negpip#16]
** Error executing callback cfg_denoiser_callback for D:\SD\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\script_callbacks.py", line 216, in cfg_denoiser_callback
        c.callback(params)
      File "D:\SD\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py", line 191, in denoiser_callback
        for step, regions in self.conds_all[0]:
    TypeError: 'NoneType' object is not subscriptable

**Comment by hako-mikan** [comment]
You are using an old version.
Please update it and test.

**Comment by JujoHotaru** [comment]
@hako-mikan 

いつもお世話になっております。

本件関連かもしれませんが、本日時点の最新リビジョン（6ac99603）で、txt2imgではなくimg2imgを行う際にNegPiPが有効になっているとステップ毎にエラーメッセージが出るようです（画像生成は行われます）。  
プロンプトにマイナス要素が無くても発生しました。

```
** Error executing callback cfg_denoiser_callback for C:\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 216, in cfg_denoiser_callback
        c.callback(params)
      File "C:\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py", line 236, in denoiser_callback
        for step, regions in self.conds_all[0]:
    TypeError: 'NoneType' object is not subscriptable
```

**Comment by ArnorWing** [comment]
Make sure you add ",negpip" to Adetailer script names in settings.
This fixed this issue for me.

**Comment by tunak222** [comment]
i have the same problem,im already on latest version of webui,latest version of negpip and already added negpip to adetailer script names,the problem only happens when generating an img on text2img and then generating an img on img2img,or when generating an img on img2img and then generating another img on text2img

**Comment by hako-mikan** [comment]
This error is displayed when the script is unable to set values properly before denoising. Possible reasons could be that the script, like ADetailer, hasn't been loaded, or there might be an error occurring midway. The first thing I'd like you to check is whether any error occurred before this one. If not, it's possible that additional denoising, similar to ADetailer, is being conducted without other scripts.

このエラーはスクリプトがデノイズ前に正常に値を設定できていないときに表示されます。
可能性としてはADetailerのようにスクリプトの読み込みが行われていないときや、途中でエラーが起きている可能性です。まず確認してもらいたいのがこのエラーの前に何らかのエラーが発生していないかです。発生していない場合にはADetailerのように追加のデノイズが他のスクリプト抜きで行われている可能性があります。

**Comment by JujoHotaru** [comment]
@hako-mikan 確認してみたところ、当該エラーの前にエラーは出ていないようでした。
他拡張機能との相性問題なのかもしれませんが、特にLoRAやプロンプト拡張の類なども使っていない状態で、img2imgを実行するだけで発生するようになりました。
私のところもADetailer用の設定変更は適用済みとなっています。

**Comment by Priestru** [comment]
> negp

Tho

> Make sure you add ",negpip" to Adetailer script names in settings. This fixed this issue for me.

Thank you! This solved issue for me!

**Comment by ArnorWing** [comment]
> > Make sure you add ",negpip" to Adetailer script names in settings. This fixed this issue for me.
> 
> Thank you! This solved issue for me!

I still have this error, it is not fixed. It returned soon after i wrote that last time.

**Comment by zzz7xz** [comment]
Similar errors occur here.
After generating t2i, switching to i2i and generating the image causes errors. The reverse case is also the same.
The effect of this extension itself seems to be fine.

webui and this extension are up to date,
script name has already been added to adetailer.

```
** Error executing callback cfg_denoiser_callback for J:\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py
    Traceback (most recent call last):
      File "J:\stable-diffusion-webui\modules\script_callbacks.py", line 216, in cfg_denoiser_callback
        c.callback(params)
      File "J:\stable-diffusion-webui\extensions\sd-webui-negpip\scripts\negpip.py", line 264, in denoiser_callback
        for step, regions in self.hr_conds_all[0] if self.hrp and self.hr else  self.conds_all[0]:
    TypeError: 'NoneType' object is not subscriptable
```
