### ISSUE TITLE
Not work well with prompt editing

### ISSUE THREAD

**Issue by Ando-Lin** [hako-mikan/sd-webui-negpip#17]
The plugin doesn't work well with Prompt Editing and Prompts like the following don't work as expected:
[cat:(abc:-1):0.5]
Normally, the "abc" will appear only when the sample is 1/2 way through, but with the plugin enabled the "abc" appears earlier and interferes with the results.
Another example is that [cat:(abc:-1):0.99] should be equivalent to "cat", but with the plugin enabled it is equivalent to "cat,(abc:-1)".

**Comment by hako-mikan** [comment]
![test](https://github.com/hako-mikan/sd-webui-negpip/assets/122196982/f953c219-d0d8-412b-a9e2-8cef56417c12)
Tested with the following prompts
```
rose tree and [cat:(red:-1.5):0.01]
rose tree and [cat:(red:-1.5):0.5]
rose tree and [cat:(red:-1.5):0.99]
```
Roses are usually red.
`rose tree and [cat:(red:-1.5):0.01]` is equivalent to `rose tree and (red:-1.5)`, so there are only white roses.
`rose tree and [cat:(red:-1.5):0.99]` is equivalent to `rose tree and cat`, so there are red roses and a cat.
`rose tree and [cat:(red:-1.5):0.5]` is in between both, so you get a pink rose and a cat.
