### ISSUE TITLE
Auto deactivate extension when prompt doesn't contain negative weights

### ISSUE THREAD

**Issue by light-and-ray** [hako-mikan/sd-webui-negpip#24]
Even if I don't add negative weights, but extension is active, generation speed drops a bit. In my case it is from 25.5s to 26.3s for batch size of 10 images. It is not significant, but it is bad

You should add check if prompt contains negative weights, and automatically deactivate extension for the generation if it doesn't contain negative weights

**Comment by Neverdusk** [comment]
Adding to this, I seem to keep getting error messages on each step of generation when the extension is enabled but there aren't any negative weights.

**Comment by hako-mikan** [comment]
Fixed.
