### ISSUE TITLE
If I put a minus in a negative prompt, does it apply as a positive prompt?

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-negpip#26]
I understand that it works by putting minus in the positive prompt window,

On the contrary, if I put a minus in the negative prompt window, does it work as a positive prompt?

**Comment by hako-mikan** [comment]
As described in Introduction, it works as a positive prompt.
`By checking the "Active" box, it will become effective. In the prompt input screen, entering a negative value like (word:-1) will give it a negative effect. It also works with negative prompts, in which case it will have a positive effect.`
