### ISSUE TITLE
Incompatible with Regional Prompter

### ISSUE THREAD

**Issue by ThereforeGames** [hako-mikan/sd-webui-negpip#27]
Hi,

This plugin is a gamechanger! However, it causes the following crash when used in conjunction with [Regional Prompter](https://github.com/hako-mikan/sd-webui-regional-prompter):

```
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 1 for tensor number 1 in the list.
```

Let me know if more diagnostic info is required.

**Comment by hako-mikan** [comment]
NegPiP and Regional Prompter are designed to coexist. Please tell me what settings caused that error.

**Comment by hako-mikan** [comment]
I tested with your settings in Web-UI 1.7.0.
There is no error, so bug may be fixed.
Please test it.
