### ISSUE TITLE
Extension fails when using Textual Embeddings with negative weights 

### ISSUE THREAD

**Issue by zcatharisis** [hako-mikan/sd-webui-negpip#29]
I saw your tweet about Auto1111 not having the option to disable Negative Prompts in its pipeline, as this extension could perform that role instead. I thought to try that myself, using my usual negative prompts but instead with a negative weight in the positive prompts. When I tried using an embedding with a negative weight though, it spat out an error and all negatively weighted prompts were discarded in the resulting images, even those that weren't embeddings. 

This isn't a feature or bug request though, more putting the info out there that this functionality isn't currently supported. I would have posted this as a discussion if the repository had one. It'd be great if this supports embeddings in the future, but it's a plenty great extension as it is. I was only curious if using this with negative_hand could have improved hand generation.

**Comment by BurnZeZ** [comment]
What is necessary to implement this?
Why was this issue closed?

**Comment by zcatharisis** [comment]
> What is necessary to implement this? Why was this issue closed?

Not sure, maybe because negatively weighing embeddings would require a rewrite of the whole code, or more likely because hako-mikan isn't interested in implementing it in the first place. I closed it after I was sure hako-mikan at least saw this post, and recognized that it wasn't going to be worked on.
