### ISSUE TITLE
Prompt editing go wrong

### ISSUE THREAD

**Issue by cololy** [hako-mikan/sd-webui-negpip#3]
When negpip is enabled, prompt editing go wrong.

Prompt example:
[(Black:-1.0) 1girl:Tiger:999]

When negpip is disabled, of cource, the prompt "Tiger" doesn't affect the output image. This is correct behavior.
However, when negpip is enabled, the output images seems to be affected by the prompt "Tiger".

This issue also occurs without negative prompt, like "[1girl:Tiger:999]".

**Comment by hako-mikan** [comment]
Supporting now.

**Comment by cololy** [comment]
I tested and it works. Thank you for update!
