### ISSUE TITLE
複数タグに対するnegpipの最も適切な表記方法について

### ISSUE THREAD

**Issue by tomsy127** [hako-mikan/sd-webui-negpip#42]
細かいことだとは思いますが、明確な正解を見つけられなかったので質問させてください。

例えば、greyscaleとmonochromeをネガティブ扱いにしたい場合、想定されている最も適切な書き方は下記のうち（またはそれ以外で）どれでしょうか？
①1girl, standing, smile (greyscale:-1) (monochrome:-1)
②1girl, standing, smile (greyscale:-1), (monochrome:-1)
④1girl, standing, smile (greyscale monochrome:-1)
④1girl, standing, smile (greyscale, monochrome:-1)

**Comment by hako-mikan** [comment]
カンマのあるなしについてはあまり関係がないです。(greyscale, monochrome:-1)と(greyscale:-1) (monochrome:-1)には違いが出る場合がありますが、今回のような意味の似ている言葉ならどちらでも変わりません。

　redとappleのようなwordだと(red apple)と(red)と(apple)の場合では違いでるかもしれません。SD1.X系統では違いが出ないと思いますが、XLやFLUXなどのプロンプトにある程度従順なモデルだとred appleというつながりも意味が出てくるので。こればっかりは試してみないと分からないですね。
