### ISSUE TITLE
how to do use this to comfyui and flux?

### ISSUE THREAD

**Issue by Lagrebanana** [hako-mikan/sd-webui-negpip#47]
need this for comfyui and flux☺️

**Comment by hako-mikan** [comment]
It is beyond my ability, so I cannot handle up to Comfy.
I have outlined the principles below, so I believe it would be faster to ask someone who is creating the Comfy nodes for assistance.
https://civitai.com/articles/8008/the-mechanism-of-negpip-and-flux-support
