### ISSUE TITLE
[feature req] 

### ISSUE THREAD

**Issue by za-wa-n-go** [hako-mikan/sd-webui-negpip#48]
Recently, ComfyUI has become a major tool, so I would be very happy if NegPip could also work with ComfyUI.

**Comment by hako-mikan** [comment]
It is beyond my ability, so I cannot handle up to Comfy.
I have outlined the principles below, so I believe it would be faster to ask someone who is creating the Comfy nodes for assistance.
https://civitai.com/articles/8008/the-mechanism-of-negpip-and-flux-support

**Comment by pamparamm** [comment]
@za-wa-n-go I've added FLUX support into NegPip implementation from https://github.com/pamparamm/ComfyUI-ppm
