### ISSUE TITLE
Blacket parsing missed?

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-negpip#6]
For example,

```
1girl, (open mouth), pink hair, (cat ear:-1)
```

This prompt with NegPiP results : (in console output)

```
[['open mouth, pink hair, cat ear', '-1']]
[]
NegPiP enable, Positive:[9],Negative:None
```

`open mouth, pink hair` is treated as negative.

---------------

いつも便利に活用させていただいております。  
さて、プロンプトのマイナス指定する部分より前で強調カッコを使っていると、その先頭位置からのプロンプトがすべてマイナス解釈されてしまうようなのですが、これは不具合か仕様か判断できずIssue起草させていただきました。  
他の拡張機能類はオフにしているつもりなのですが、万一そのあたりの影響がありましたらご容赦ください。  
よろしくお願いいたします。

**Comment by JujoHotaru** [comment]
ご確認ありがとうございました。修正よろしくお願いいたします。  
余談ながら #5 に私も引っかかっております。こちらもご確認いただければ幸いです。

**Comment by hako-mikan** [comment]
修正しました。
#5が出る条件などありましたら教えてもらえると嬉しいです。
web-ui 1.6の環境では再現しませんでした。

**Comment by JujoHotaru** [comment]
ご対応ありがとうございました。
#5 のほう、確かにいつでも発生するわけではないので、発生条件がわかりましたら報告いたします。
